export const FETCH_SIGNUP_BEGINS = 'FETCH_SIGNUP_BEGINS';
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS';
export const FETCH_SIGNUP_FAILURE = 'FETCH_SIGNUP_FAILURE';
export const SIGNIN_BEGINS = 'SIGNIN_BEGINS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
